# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1047, 672)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(380, 60, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.text_Plaintext = QtWidgets.QTextEdit(Dialog)
        self.text_Plaintext.setGeometry(QtCore.QRect(170, 160, 241, 71))
        self.text_Plaintext.setObjectName("text_Plaintext")
        self.text_Information = QtWidgets.QTextEdit(Dialog)
        self.text_Information.setGeometry(QtCore.QRect(560, 160, 241, 71))
        self.text_Information.setObjectName("text_Information")
        self.text_Cipher = QtWidgets.QTextEdit(Dialog)
        self.text_Cipher.setGeometry(QtCore.QRect(170, 290, 241, 71))
        self.text_Cipher.setObjectName("text_Cipher")
        self.text_Signature = QtWidgets.QTextEdit(Dialog)
        self.text_Signature.setGeometry(QtCore.QRect(560, 290, 241, 71))
        self.text_Signature.setObjectName("text_Signature")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 190, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 320, 51, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(630, 90, 91, 20))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(200, 430, 47, 13))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(330, 430, 47, 13))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(580, 430, 47, 13))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(740, 430, 47, 13))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.btn_Encrypt = QtWidgets.QPushButton(Dialog)
        self.btn_Encrypt.setGeometry(QtCore.QRect(170, 430, 75, 23))
        self.btn_Encrypt.setObjectName("btn_Encrypt")
        self.btn_Decrypt = QtWidgets.QPushButton(Dialog)
        self.btn_Decrypt.setGeometry(QtCore.QRect(320, 430, 75, 23))
        self.btn_Decrypt.setObjectName("btn_Decrypt")
        self.btn_Sign = QtWidgets.QPushButton(Dialog)
        self.btn_Sign.setGeometry(QtCore.QRect(570, 430, 75, 23))
        self.btn_Sign.setObjectName("btn_Sign")
        self.btn_verytify = QtWidgets.QPushButton(Dialog)
        self.btn_verytify.setGeometry(QtCore.QRect(710, 430, 75, 23))
        self.btn_verytify.setObjectName("btn_verytify")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(470, 180, 61, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(470, 320, 47, 13))
        self.label_10.setObjectName("label_10")
        self.btn_generate_key = QtWidgets.QPushButton(Dialog)
        self.btn_generate_key.setGeometry(QtCore.QRect(650, 90, 75, 23))
        self.btn_generate_key.setObjectName("btn_generate_key")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "RSA Cipher"))
        self.label_2.setText(_translate("Dialog", "Plaintext"))
        self.label_3.setText(_translate("Dialog", "Ciphertext"))
        self.btn_Encrypt.setText(_translate("Dialog", "Encrypt"))
        self.btn_Decrypt.setText(_translate("Dialog", "Decrypt"))
        self.btn_Sign.setText(_translate("Dialog", "Sign"))
        self.btn_verytify.setText(_translate("Dialog", "Verify"))
        self.label_9.setText(_translate("Dialog", "Information"))
        self.label_10.setText(_translate("Dialog", "Signature"))
        self.btn_generate_key.setText(_translate("Dialog", "generate_key"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
